In [1]:
import torch
import numpy as np

# Tensors

In [2]:
# Creating Tensor
a = torch.Tensor([1,2,3])
b = torch.Tensor(3,3)

In [3]:
# Tensor and Ndarray conversion
c = a.numpy()
a_recovered = torch.from_numpy(c)

In [4]:
# Initialization of Tensors
B, C, H, W = 2, 3, 8, 10
x = torch.rand(B, C, H, W)
f = torch.randn(B, H, W)

In [5]:
# Reshaping Tensors
BATCH_SIZE = 4
SEQ_LENGTH = 8
NUM_CHANNELS = 3
HEIGHT = 8
WIDTH = 8

features = torch.randn(BATCH_SIZE, SEQ_LENGTH, NUM_CHANNELS, HEIGHT, WIDTH)
linear_features = features.view(BATCH_SIZE * SEQ_LENGTH, NUM_CHANNELS * HEIGHT * WIDTH)
linear_features_2 = features.view(BATCH_SIZE, -1, NUM_CHANNELS, HEIGHT * WIDTH)
print(features.shape)
print(linear_features.shape)
print(linear_features_2.shape)

torch.Size([4, 8, 3, 8, 8])
torch.Size([32, 192])
torch.Size([4, 8, 3, 64])


### Other interesting operations on Tensors:
1. Cat
2. Stack
3. Squeeze
4. Unsqueeze
5. Transposing
6. Permuting

# CUDA Tensors

In [6]:
torch.cuda.is_available()

True

In [7]:
torch.cuda.device_count()

1

### Following is not the best option. If GPU is not available we will get error, and also we have to manually make sure that all of the Tensors are on GPU

In [8]:
x, y = torch.ones(2), torch.ones(2)
x = x.cuda()
z = x + y

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Following ensures that Tensors are always on the same device (if GPU is available they will both be on GPU, otherwise they will both be on CPU)

In [9]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [10]:
x, y = torch.ones(2), torch.ones(2)
x = x.to(device)
y = y.to(device)
z = x + y
z

tensor([2., 2.], device='cuda:0')

In [11]:
q = torch.ones(5, device=device)
q

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [12]:
q = q.cpu()
q

tensor([1., 1., 1., 1., 1.])

In [13]:
q = q.cuda()
q

tensor([1., 1., 1., 1., 1.], device='cuda:0')

In [15]:
q = q.cpu()
q

tensor([1., 1., 1., 1., 1.])

In [16]:
q = q.to("cuda")
q

tensor([1., 1., 1., 1., 1.], device='cuda:0')